# Generated by Django 4.0 on 2021-12-28 22:04

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField(max_length=120)),
                ('model_name', models.TextField(max_length=120)),
                ('color', models.TextField(max_length=120)),
                ('jan_code', models.TextField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=todos.models.upload_image_path)),
            ],
        ),
    ]
